services:
  ielts_training_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ielts_training_app
    container_name: ielts_training_app
    networks:
      - ielts_network
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRED: ${JWT_ACCESS_TOKEN_EXPIRED}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_TOKEN_EXPIRED: ${JWT_REFRESH_TOKEN_EXPIRED}
      MAILER_USER: ${MAILER_USER}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALL_BACK_URL: ${GOOGLE_CALL_BACK_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      AI_MICROSERVICE_SECRET: ${AI_MICROSERVICE_SECRET}
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3000:3000'
    volumes:
      - ./src:/src
      - ./prisma:/prisma
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - ielts_network
    restart: always
    volumes:
      - redis_data:/data

  ai_crawler:
    build:
      context: ../ielts_ai
    container_name: ai_crawler
    networks:
      - ielts_network
    ports:
      - '8000:8000'
    environment:
      NESTJS_API_URL: http://ielts_training_app:3000/test/import-from-ai
      AI_MICROSERVICE_SECRET: ${AI_MICROSERVICE_SECRET}
    depends_on:
      - ielts_training_app

networks:
  ielts_network:
    driver: bridge

volumes:
  redis_data:
